all: DesImageSolution.java DesSolution.java DigitalSignatureSolution.java
	javac DesImageSolution.java DesSolution.java DigitalSignatureSolution.java

clean:
	rm DesImageSolution.class
	rm DesSolution.class
	rm DigitalSignatureSolution.class
